# Generated by Django 5.2.7 on 2025-11-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=150)),
                ('escuela_procedencia', models.CharField(max_length=150)),
                ('grado_inscribir', models.CharField(max_length=50)),
                ('motivo_cambio', models.TextField(blank=True)),
                ('nombre_tutor', models.CharField(max_length=150)),
                ('telefono_tutor', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
